### ISSUE TITLE
Clicking home should bring up the player's page

### ISSUE THREAD

**Issue by timothyplummer** [CodeCrow/talesofvalor_python#104]
### Description
Clicking the home button should bring up '/en/players/{username}/' instead of an empty screen

### Steps to reproduce
1. Log in as any valid player
2. Click the 'Home' link on the side bar

### Expected outcome
User should be directed to their player page.

### Current outcome
User is shown an empty page

**Comment by CodeCrow** [comment]
The "home" page is actually the ToV home page that might have news or a description of ToV in general, I think.   Clicking on the player name in the top right brings you to the player home page.

**Comment by CodeCrow** [comment]
Had a conversation with Nick.   Because clicking on the player name in the top right brings the player to the player "home page", clicking "home" should bring them to the home page for the site. (which is, yes, currently blank)
