### ISSUE TITLE
Clicking 'Choose file' as non-admin brings up a error page

### ISSUE THREAD

**Issue by timothyplummer** [CodeCrow/talesofvalor_python#105]
### Description
Clicking the 'Choose file' link as a non-admin when making a character brings up a error page where it asks you to log in as an admin. 

### Steps to reproduce
1. Log in as any non-admin player that doesn't have a character yet
2. Click the 'Add Character' link in the top right of the page
3. Click 'Choose file'

### Expected outcome
there are two options here:
1. the non-admin users should not see the link to choose file
2. a file browser window should open and allow the user to select a file from their computer

### Current outcome
a error page asking the user to log in as a admin is shown.

**Comment by CodeCrow** [comment]
Simplified to fix.
