### ISSUE TITLE
Unable to remove items from Cart

### ISSUE THREAD

**Issue by timothyplummer** [CodeCrow/talesofvalor_python#106]
### Description
After adding an item to the cart you can not remove it

### Steps to reproduce
1. Log in as any valid player
2. Click 'Registration' under events 
3. Select any amount of items to add to the cart
4. Click 'Register' button
5. Click red 'Remove' button

### Expected outcome
The page should show a success message and the items added to the cart should be removed. 

### Current outcome
403 error page

**Comment by CodeCrow** [comment]
Done!
