### ISSUE TITLE
If player pronouns are too long the user should not be created 

### ISSUE THREAD

**Issue by timothyplummer** [CodeCrow/talesofvalor_python#107]
### Description
 If the user puts in a long string for pronouns the program will spit back an error page, but the user was created just without pronouns

### Steps to reproduce
1. click Register
2. enter all needed information
3. for pronouns add something very long (I was testing for code injection at the time so there was a very long script tag in the field)
4. click register

### Expected outcome
the registration page should be shown saying that your chosen pronouns are too long and the user is not created.

### Current outcome
an error page is shown, but at the same time a user was created just their pronouns are blank. when logging in it doesn't tell the user to change their pronouns either.

**Comment by CodeCrow** [comment]
Added limit to form field to prevent this from happening.
