### ISSUE TITLE
Check to see if a user is already register for an event 

### ISSUE THREAD

**Issue by timothyplummer** [CodeCrow/talesofvalor_python#114]
### Description
If a user is already registered for an event, they shouldn't be allowed reregister for the same event. instead they should be allowed to edit their registration

### Steps to reproduce
1. Log in as a non-admin player
2. click register for an event
3. fill out the form
4. click register
5. submit payment with a developer PayPal account 
6. click register for the same event

### Expected outcome
A page that shows the current info for the registration should be shown, with an option to edit the info 

### Current outcome
the ability to reregister for the event is shown

**Comment by CodeCrow** [comment]
Just the detail is going to be shown.  You'll probably have to contact staff to update an already completed registration.
