### ISSUE TITLE
cost to register, without a meal plan, should just be the item cost 

### ISSUE THREAD

**Issue by timothyplummer** [CodeCrow/talesofvalor_python#121]
<img width="1080" alt="Screen Shot 2022-04-14 at 12 49 08 PM" src="https://user-images.githubusercontent.com/92329024/163492582-2c7a969c-d179-462a-8493-ad4aff40428c.png">

**Steps to Reproduce**
1. create a new event 
2. add an item to the event with the cost of 50.00
3. register for the event selecting the item you made in step 2
4. Make sure that you don't add a meal plan
5. click register
6. Note the cost of the item on this page, should be 50.00
7. click pay with PayPal button
8. Log in with a developer account

**Expected Result**
the cost of the item should not have changed. it should still be 50.00

**Actual Results**
the cost of the item has changed to 75.00

**Comment by CodeCrow** [comment]
Old code interfering with new, better code.
